"use client"

import type { Metadata } from "next";
import "./globals.css";
import ReactQueryProvider from "./utils/ReactQueryProvider";
import NavBar from './utils/NavBar';
import React, { useEffect, useState } from 'react';
import { Typography } from "@mui/material";
/*
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
*/
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isAuthenticated, setIsAuthenticated] = useState<boolean>(false);

  useEffect(() => {
    const userId = localStorage.getItem('id');
    setIsAuthenticated(!!userId); // Verifica si hay un userId en el localStorage
  }, []);

  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          {isAuthenticated && <NavBar/>} {/* Mostrar NavBar solo si el usuario está autenticado */}
          <main>
            {children}
          </main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
